// SPDX-License-Identifier: Apache-2.0

import { KtCodegenController } from "../src/KtCodegenController.js";
import { KtCodegenItem } from "../src/KtCodegenItem.js";

/** 创建同时覆盖 CAA/Qt 双向更新分支的共享参数测试数据。 */
export function ktCodegenCreateDialogUpdateController(): KtCodegenController {
  const controller = new KtCodegenController();
  controller.param.namePrefix = "Kt";
  controller.param.nameMiddle = "CourseGuard";
  controller.param.nameSpace = "KtWsp";
  controller.param.items.splice(
    0,
    controller.param.items.length,
    ...[
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 1,
        paramString: "Axis_Vector",
        dataType: "CATMathVector",
        component: "Spinner",
        componentCount: 1,
        isParamDlg: true,
        unit: "mm",
        notes: "CAA vector",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 2,
        paramString: "Samples",
        dataType: "CATRawColldouble",
        component: "Spinner",
        componentCount: 2,
        unit: "mm",
        notes: "one based list",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 3,
        paramString: "Enabled",
        dataType: "CATBoolean",
        component: "CheckButton",
        componentCount: 1,
        notes: "boolean cast",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 4,
        paramString: "Flags",
        dataType: "int",
        component: "CheckButtonGroup",
        componentCount: 2,
        notes: "bit flags",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 5,
        paramString: "Mode",
        dataType: "GuardMode",
        tcKind: "tk_integer",
        component: "RadioButton",
        componentCount: 1,
        notes: "enum radio",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 6,
        paramString: "Index",
        dataType: "int",
        component: "ComboBox",
        componentCount: 1,
        notes: "integer combo",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 7,
        paramString: "Bad_Combo",
        dataType: "KtString",
        component: "ComboBox",
        componentCount: 1,
        notes: "unsupported combo type",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 8,
        paramString: "OriginSpec",
        dataType: "CATISpecObject_var",
        component: "SelectorList",
        componentCount: 1,
        notes: "coordinate fallback",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 9,
        paramString: "Thresholds",
        dataType: "double",
        component: "Editor",
        componentCount: 2,
        notes: "editor list",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 10,
        paramString: "No_Action",
        dataType: "double",
        component: "Spinner",
        componentCount: 0,
        notes: "zero controls",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 11,
        paramString: "Unsupported",
        dataType: "int",
        component: "Toggle",
        componentCount: 1,
        notes: "unknown CAA control",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 12,
        paramString: "Count",
        dataType: "int",
        component: "Spinner",
        componentCount: 1,
        notes: "round from spinner",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 13,
        paramString: "Wrong_List",
        dataType: "UnknownList",
        component: "Spinner",
        componentCount: 2,
        notes: "invalid list type",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 14,
        paramString: "Scale",
        dataType: "double",
        component: "ComboBox",
        componentCount: 1,
        notes: "double combo",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 15,
        paramString: "Label",
        dataType: "CATUnicodeString",
        component: "ComboBox",
        componentCount: 1,
        notes: "unicode combo",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 16,
        paramString: "AxisSpec",
        dataType: "CATISpecObject_var",
        component: "SelectorList",
        componentCount: 1,
        notes: "absolute fallback",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 17,
        paramString: "Text_Value",
        dataType: "CATUnicodeString",
        component: "Editor",
        componentCount: 1,
        notes: "text editor",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 18,
        paramString: "Push",
        dataType: "int",
        component: "PushButton",
        componentCount: 1,
        notes: "allowed no action",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 19,
        paramString: "Lower_Spinner",
        dataType: "double",
        component: "spinner",
        componentCount: 1,
        notes: "case sensitive component",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 1,
        paramString: "Selected_Spec",
        dataType: "CATISpecObject_var",
        component: "QListWidget",
        componentCount: 1,
        notes: "field widget",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 2,
        paramString: "Axis_Vector",
        dataType: "CATMathVector",
        component: "QDoubleSpinBox",
        componentCount: 1,
        isParamDlg: true,
        unit: "mm",
        notes: "Qt vector",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 3,
        paramString: "Float_Values",
        dataType: "ListKtfloat",
        component: "QDoubleSpinBox",
        componentCount: 2,
        notes: "legacy asymmetric list",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 4,
        paramString: "Count",
        dataType: "int",
        component: "QDoubleSpinBox",
        componentCount: 1,
        notes: "round to integer",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 5,
        paramString: "Number",
        dataType: "int",
        component: "QSpinBox",
        componentCount: 1,
        notes: "integer spinner",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 6,
        paramString: "Flags",
        dataType: "int",
        component: "QCheckBoxGroup",
        componentCount: 2,
        notes: "bit flags",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 7,
        paramString: "Mode",
        dataType: "GuardMode",
        tcKind: "tk_integer",
        component: "QRadioButton",
        componentCount: 1,
        notes: "enum radio",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 8,
        paramString: "Index",
        dataType: "uint32_t",
        component: "QComboBox",
        componentCount: 1,
        notes: "integer combo",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 9,
        paramString: "Title",
        dataType: "QString",
        component: "QComboBox",
        componentCount: 1,
        notes: "Qt string combo",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 10,
        paramString: "Kt_Name",
        dataType: "KtString",
        component: "QComboBox",
        componentCount: 1,
        notes: "legacy placeholder",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 11,
        paramString: "Text_Value",
        dataType: "KtString",
        component: "QLineEdit",
        componentCount: 1,
        isParamDlg: true,
        notes: "local string conversion",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 12,
        paramString: "No_Action",
        dataType: "int",
        component: "QSpinBox",
        componentCount: 0,
        notes: "zero controls",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 13,
        paramString: "Unsupported",
        dataType: "int",
        component: "QDial",
        componentCount: 1,
        notes: "unknown Qt control",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 14,
        paramString: "Plain_Text",
        dataType: "QString",
        component: "QLineEdit",
        componentCount: 1,
        notes: "Qt text",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 15,
        paramString: "Text_List",
        dataType: "KtString",
        component: "QLineEdit",
        componentCount: 2,
        notes: "legacy string list",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 16,
        paramString: "Numbers",
        dataType: "ListKtint",
        component: "QSpinBox",
        componentCount: 2,
        notes: "integer list",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 17,
        paramString: "Enabled",
        dataType: "bool",
        component: "QCheckBox",
        componentCount: 1,
        notes: "single checkbox",
      }),
      new KtCodegenItem({
        nameSuffix: "Qt",
        id: 18,
        paramString: "Push",
        dataType: "int",
        component: "QPushButton",
        componentCount: 1,
        notes: "directional no action",
      }),
      new KtCodegenItem({
        nameSuffix: "Caa",
        id: 0,
        paramString: "Skipped_Id",
        dataType: "int",
        component: "Spinner",
        componentCount: 1,
      }),
      new KtCodegenItem({
        nameSuffix: "Other",
        id: 1,
        paramString: "Skipped_Suffix",
        dataType: "int",
        component: "Spinner",
        componentCount: 1,
      }),
    ],
  );
  return controller;
}
